#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-eno1}" 

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE} ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

SPEED=$(cat /sys/class/net/$INTERFACE/speed)
IPADDR=$(ip addr show $INTERFACE | perl -n -e "/inet6? ([^\/]+).* scope global/ && print \$1 and exit")
#------------------------------------------------------------------------

echo "🖧$SPEED Mbits/sec $IPADDR" # full text
echo "🖧$IPADDR" # short text

# color
if [[ $SPEED -ge 1000 ]]; then
    echo "#00FF00"
elif [[ $QUALITY -ge 100 ]]; then
    echo "#FFF600"
elif [[ $QUALITY -ge 10 ]]; then
    echo "#FFAE00"
else
    echo "#FF0000"
fi
